name: Manually Build and Push

on: 
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    
    - run: |-
        gcloud --quiet auth configure-docker

    - name: Build
      run: |-
        docker build \
          --tag gcr.io/kgdata-kompas/kgmedia-etl:$(git rev-parse --short HEAD) .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push gcr.io/kgdata-kompas/kgmedia-etl:$(git rev-parse --short HEAD) 

    - name: Image
      run: |-
        echo gcr.io/kgdata-kompas/kgmedia-etl:$(git rev-parse --short HEAD)
